config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: [ :index, :show, :new, :create ] do
    resources :bookmarks, only: [ :new, :create, :destroy ]
  end
  resources :bookmarks, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }

  belongs_to :movie
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true

  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update]

  def index
    @lists = List.all
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to List.last
    else
      render :new
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <div class="text-center">
    <%= simple_form_for [@list, @bookmark] do |f| %>
      <%= f.association :movie %>
      <%= f.input :comment %>
      <%= f.submit class:'btn btn-primary' %>
    <% end %>
    <%= link_to 'Cancel', lists_path, class:'btn btn-danger' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <h1 class="text-center">Your Lists</h1>
  <%= link_to "Create a new list!", new_list_path, class:"btn btn-primary" %>
  <div class="row">
      <% @lists.each do |list| %>
        <h2 class="name"><%= list.name %></h2>
        <%= link_to "See this list", list_path(list), class:"btn btn-primary" %>
      <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <h1 class="title">Create a new list!</h1>
    <div class="form">
      <%= simple_form_for(@list) do |f| %>
        <%= f.input :name, label: 'List Name' %>
        <%= f.input :photo, as: :file %>
        <%= f.submit label: 'Create List', class:'btn btn-primary' %>
      <% end %>
    </div>
</div>

app/views/lists/show.html.erb
<div class="container">
  <h1 class='text-center'><%= @list.name %></h1>
  <%= link_to "Back to Lists", root_path, class:'btn btn-primary' %>
  <%= link_to "New Bookmark", new_list_bookmark_path(list_id:@list), class:'btn btn-primary' %>
    <div class="row">
      <% @list.bookmarks.each do |bookmark| %>
        <div class="card" style="width: 18rem;">
          <div class="card-body">
              <%= image_tag bookmark.movie.poster_url, alt: "poster", width: 100, class:"card-img-top" %>
              <h3 class="card-title"><%= bookmark.movie.title %></h3>
              <p class="card-text"><%= bookmark.movie.overview %></p>
              <h5 class="user-comment"><%= bookmark.comment %></h5>
              <%= link_to "Delete", bookmark_path(bookmark), class:"btn btn-danger", method: 'delete', data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      <% end %>
    </div>
</div>